SpecialRecipe/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from recipe.views import RecipesListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recipes/', include('recipe.urls', namespace='recipe')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', RecipesListView.as_view(), name='index'),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

accounts/urls.py
from django.urls import path

from accounts import views as account_view

app_name = 'accounts'

urlpatterns = [
    path('registration/', account_view.UserRegistrationView.as_view(), name='registration'),
    path('login/', account_view.UserLoginView.as_view(), name='login'),
    path('logout/', account_view.LogoutView.as_view(), name='logout'),

    path('user/<slug:slug>/', account_view.UserProfileView.as_view(), name='profile'),
    path('user/<slug:slug>/email/', account_view.UserProfileEmailView.as_view(), name='profile-email'),
    path('user/<slug:slug>/password/', account_view.UserProfilePasswordView.as_view(), name='profile-password'),

    path('verification/send/<str:email>/', account_view.SendVerificationEmailView.as_view(),
         name='send-verification-email'),
    path('verify/<str:email>/<uuid:code>/', account_view.EmailVerificationView.as_view(), name='email-verification'),

    path('password_reset/', account_view.PasswordResetView.as_view(), name='reset_password'),
    path('reset/<uidb64>/<token>/', account_view.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

api/urls.py
from django.urls import include, path

app_name = 'api'

urlpatterns = [
    path('', include('api.recipe.urls', namespace='recipe')),
    path('', include('api.accounts.urls', namespace='accounts')),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),

    path('', include('recipe.urls', namespace='recipe')),
    path('interactions/', include('interactions.urls', namespace='interactions')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('api/v1/', include('api.urls', namespace='api')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

accounts/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView

from accounts import forms as account_forms
from accounts.models import EmailVerification, User
from accounts.tasks import send_verification_email
from common.urls import get_referer_or_default
from common.views import LogoutRequiredMixin, TitleMixin
from utils.uid import is_valid_uuid


class UserRegistrationView(LogoutRequiredMixin, SuccessMessageMixin, TitleMixin, CreateView):
    model = User
    form_class = account_forms.UserRegistrationForm
    template_name = 'accounts/registration.html'
    success_message = 'You have successfully registered!'
    success_url = reverse_lazy('accounts:login')
    title = 'Special Recipe | Registration'


class UserLoginView(LogoutRequiredMixin, TitleMixin, auth_views.LoginView):
    form_class = account_forms.UserLoginForm
    template_name = 'accounts/login.html'
    title = 'Special Recipe | Registration'

    def get(self, request, *args, **kwargs):
        request.session['before_login_url'] = get_referer_or_default(self.request, None)
        return super().get(request, *args, **kwargs)

    def get_success_url(self):
        next_query = self.request.session.get('before_login_url')
        return next_query if next_query else reverse_lazy('accounts:profile', args={self.request.user.slug})

    def form_valid(self, form):
        remember_me = form.cleaned_data.get('remember_me')
        if not remember_me:
            self.request.session.set_expiry(0)
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, 'The entered data is incorrect, please try again.')
        return super().form_invalid(form)


class LogoutView(auth_views.LogoutView):
    def get_redirect_url(self):
        next_page = get_referer_or_default(self.request)
        return next_page


class UserProfileView(SuccessMessageMixin, TitleMixin, UpdateView):
    model = User
    form_class = account_forms.UserProfileForm
    template_name = 'accounts/profile/profile.html'
    title = 'Special Recipe | Account'
    success_message = 'Profile updated successfully!'

    def get_success_url(self):
        return reverse_lazy('accounts:profile', args=(self.object.slug,))

    def form_invalid(self, form):
        self.object.refresh_from_db()
        return super().form_invalid(form)


class UserProfilePasswordView(SuccessMessageMixin, auth_views.PasswordChangeView):
    form_class = account_forms.PasswordChangeForm
    template_name = 'accounts/profile/profile.html'
    title = 'Special Recipe | Password'
    success_message = 'Your password has been successfully updated!'

    def get_success_url(self):
        return reverse_lazy('accounts:profile-password', args={self.request.user.slug})


class UserProfileEmailView(SuccessMessageMixin, auth_views.PasswordChangeView):
    form_class = account_forms.EmailChangeForm
    template_name = 'accounts/profile/profile.html'
    title = 'Special Recipe | Email'
    success_message = 'Your email has been successfully changed!'

    def get_success_url(self):
        return reverse_lazy('accounts:profile-email', args={self.request.user.slug})


class SendVerificationEmailView(LoginRequiredMixin, TitleMixin, TemplateView):
    template_name = 'accounts/email/email_verification_done.html'
    title = 'Special Recipe | Send Verification'
    sending_interval = settings.EMAIL_SEND_INTERVAL_SECONDS

    def get(self, request, *args, **kwargs):
        email = kwargs.get('email')
        user = get_object_or_404(User, email=email)

        if not user.is_request_user_matching(request):
            raise Http404

        seconds_since_last_email = user.seconds_since_last_email_verification()

        if user.is_verified:
            messages.warning(request, 'You have already verified your email.')
        elif seconds_since_last_email < self.sending_interval:
            seconds_left = self.sending_interval - seconds_since_last_email
            messages.warning(request, f'Please wait {seconds_left} to resend the confirmation email.')
        else:
            verification = user.create_email_verification()
            send_verification_email.delay(object_id=verification.id)
        return super().get(request, *args, **kwargs)


class EmailVerificationView(TemplateView):
    template_name = 'accounts/email/email_verification_complete.html'

    def get(self, request, *args, **kwargs):
        code = kwargs.get('code')
        email = kwargs.get('email')
        user = get_object_or_404(User, email=email)

        if not user.is_request_user_matching(request) or not is_valid_uuid(str(code)):
            raise Http404

        verification = get_object_or_404(EmailVerification, user=user, code=code)

        if user.is_verified:
            messages.warning(request, 'Your email has already been verified.')
        elif not verification.is_expired():
            user.verify()
        else:
            messages.warning(request, 'The verification link has expired.')
        return super().get(request, *args, **kwargs)


class PasswordResetView(LogoutRequiredMixin, SuccessMessageMixin, auth_views.PasswordResetView):
    title = 'Special Recipe | Password Reset'
    template_name = 'accounts/password/reset_password.html'
    subject_template_name = 'accounts/password/password_reset_subject.html'
    email_template_name = 'accounts/password/password_reset_email.html'
    form_class = account_forms.PasswordResetForm
    success_url = reverse_lazy('accounts:reset_password')
    success_message = 'We’ve emailed you instructions for setting your password, if an account exists with the email ' \
                      'you entered. You should receive them shortly. If you don’t receive an email, please make sure ' \
                      'you’ve entered the address you registered with, and check your spam folder.'


class PasswordResetConfirmView(LogoutRequiredMixin, SuccessMessageMixin, TitleMixin,
                               auth_views.PasswordResetConfirmView):
    title = 'Special Recipe | Password Reset'
    template_name = 'accounts/password/password_reset_confirm.html'
    form_class = account_forms.SetPasswordForm
    success_url = reverse_lazy('accounts:login')
    success_message = 'Your password has been set. You can now sign into your account with the new password.'

api/accounts/views.py
from django.conf import settings
from django.shortcuts import get_object_or_404
from djoser import email as email_views
from rest_framework import status
from rest_framework.generics import CreateAPIView, UpdateAPIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from accounts.models import EmailVerification, User
from accounts.tasks import send_verification_email
from api.accounts.serializers import EmailVerificationSerializer
from utils.uid import is_valid_uuid


class PasswordResetEmail(email_views.PasswordResetEmail):
    template_name = 'accounts/password/password_reset_email.html'
    subject_template_name = 'accounts/password/password_reset_subject.html'


class SendVerificationEmailCreateAPIView(CreateAPIView):
    queryset = EmailVerification.objects.all()
    serializer_class = EmailVerificationSerializer
    permission_classes = (IsAuthenticated,)
    sending_interval = settings.EMAIL_SEND_INTERVAL_SECONDS

    def create(self, request, *args, **kwargs):
        email = request.data.get('email')
        user = get_object_or_404(User, email=email)

        if not user.is_request_user_matching(request):
            return Response({'detail': 'Not found.'}, status=status.HTTP_404_NOT_FOUND)
        elif user.is_verified:
            return Response({'detail': 'Already verified.'}, status=status.HTTP_400_BAD_REQUEST)

        seconds_since_last_email = user.seconds_since_last_email_verification()

        if seconds_since_last_email < self.sending_interval:
            seconds_left = self.sending_interval - seconds_since_last_email
            response = {
                'detail': 'Messages per minute limit reached.',
                'seconds_left': seconds_left,
            }
            return Response(response, status=status.HTTP_429_TOO_MANY_REQUESTS)
        else:
            verification = user.create_email_verification()
            send_verification_email.delay(object_id=verification.id)
            serializer = self.get_serializer(verification, partial=True)
            return Response(serializer.data, status=status.HTTP_201_CREATED)


class EmailVerificationUpdateAPIView(UpdateAPIView):
    queryset = User.objects.all()
    permission_classes = (IsAuthenticated,)

    def update(self, request, *args, **kwargs):
        code = request.data.get('code')
        email = request.data.get('email')
        user = get_object_or_404(User, email=email)

        if not user.is_request_user_matching(request) or not is_valid_uuid(str(code)):
            return Response({'detail': 'Not found.'}, status=status.HTTP_404_NOT_FOUND)
        elif user.is_verified:
            return Response({'detail': 'Already verified.'}, status=status.HTTP_400_BAD_REQUEST)

        verification = get_object_or_404(EmailVerification, user=user, code=code)
        if not verification.is_expired():
            user.verify()
            return Response(status=status.HTTP_204_NO_CONTENT)
        else:
            return Response({'detail': 'Link was expired.'}, status=status.HTTP_410_GONE)

api/views/accounts.py
from django.conf import settings
from django.shortcuts import get_object_or_404
from djoser import email as email_views
from rest_framework import status
from rest_framework.generics import CreateAPIView, UpdateAPIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from accounts.models import EmailVerification, User
from accounts.tasks import send_verification_email
from api.serializers.accounts import EmailVerificationSerializer
from utils.uid import is_valid_uuid


class PasswordResetEmail(email_views.PasswordResetEmail):
    template_name = 'accounts/password/password_reset_email.html'
    subject_template_name = 'accounts/password/password_reset_subject.html'


class SendVerificationEmailCreateAPIView(CreateAPIView):
    queryset = EmailVerification.objects.all()
    serializer_class = EmailVerificationSerializer
    permission_classes = (IsAuthenticated,)
    sending_interval = settings.EMAIL_SEND_INTERVAL_SECONDS

    def create(self, request, *args, **kwargs):
        email = request.data.get('email')
        user = get_object_or_404(User, email=email)

        if not user.is_request_user_matching(request):
            return Response({'detail': 'Not found.'}, status=status.HTTP_404_NOT_FOUND)
        elif user.is_verified:
            return Response({'detail': 'Already verified.'}, status=status.HTTP_400_BAD_REQUEST)

        seconds_since_last_email = user.seconds_since_last_email_verification()

        if seconds_since_last_email < self.sending_interval:
            seconds_left = self.sending_interval - seconds_since_last_email
            response = {
                'detail': 'Messages per minute limit reached.',
                'seconds_left': seconds_left,
            }
            return Response(response, status=status.HTTP_429_TOO_MANY_REQUESTS)
        else:
            verification = user.create_email_verification()
            send_verification_email.delay(object_id=verification.id)
            serializer = self.get_serializer(verification, partial=True)
            return Response(serializer.data, status=status.HTTP_201_CREATED)


class EmailVerificationUpdateAPIView(UpdateAPIView):
    queryset = User.objects.all()
    permission_classes = (IsAuthenticated,)

    def update(self, request, *args, **kwargs):
        code = request.data.get('code')
        email = request.data.get('email')
        user = get_object_or_404(User, email=email)

        if not user.is_request_user_matching(request) or not is_valid_uuid(str(code)):
            return Response({'detail': 'Not found.'}, status=status.HTTP_404_NOT_FOUND)
        elif user.is_verified:
            return Response({'detail': 'Already verified.'}, status=status.HTTP_400_BAD_REQUEST)

        verification = get_object_or_404(EmailVerification, user=user, code=code)
        if not verification.is_expired():
            user.verify()
            return Response(status=status.HTTP_204_NO_CONTENT)
        else:
            return Response({'detail': 'Link was expired.'}, status=status.HTTP_410_GONE)

templates/accounts/password/password_reset_confirm.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
  <div class="container bg-light min-vh-100">
    <div class="row">
      {% if validlink %}
        <div class="container bg-secondary-subtle rounded-4 mt-5 col-md-4 shadow-lg">
          <form action="" method="POST">

            {% csrf_token %}

            <h2 class="text-center mt-2">New password creation</h2>
            <p>Create a new password for your account, it must be different from the old one.</p>
            {% if form.errors %}
              <div class="alert alert-warning" role="alert">
                {% for field, errors in form.errors.items %}
                  {% for error in errors %}
                    <ul class="m-0">
                      <li>
                        {{ error }}
                      </li>
                    </ul>
                  {% endfor %}
                {% endfor %}
              </div>
            {% endif %}
            <div class="mb-4">
              <label for="{{ form.new_password1.id_for_label }}" class="form-label">New password</label>
              {{ form.new_password1 }}
            </div>
            <div class="mb-4">
              <label for="{{ form.new_password2.id_for_label }}" class="form-label">New password confirmation</label>
              {{ form.new_password2 }}
            </div>
            <div class="text-center mb-3">
              <button type="submit" class="btn btn-outline-success">Reset my password</button>
            </div>
          </form>
        </div>
      {% else %}
        <div class="text-center container col-md-10">
          <h2 class="mt-2">Password reset unsuccessful</h2>
          <h4 class="alert alert-warning">
            The password reset link was invalid, possibly because it has already been used.
            Please request a new password reset.
          </h4>
          <h3 class="mb-3">
            Click
            <a class="text-decoration-none" href="{% url 'accounts:reset_password' %}">
              here
            </a>
            to go to the forgot password page.
          </h3>
        </div>
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/accounts/password/password_reset_email.html
{% autoescape off %}
Hello, {{ user.username }}!

We received a request to reset the password for your account for this email address. To initiate the password reset process for your account, click the link below.

{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

This link can only be used once. If you need to reset your password again, please visit {{ protocol }}://{{domain}}{% url 'accounts:reset_password' %} and request another reset.

If you did not make this request, you can simply ignore this email.

The Special Recipe Team

{% endautoescape %}

templates/accounts/password/password_reset_subject.html
{% autoescape off %}
Special Recipe | Password reset

{% endautoescape %}

templates/accounts/password/reset_password.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
  <div class="container bg-light min-vh-100">
    <div class="row">
      <div class="container bg-secondary-subtle rounded-4 mt-5 col-md-4 shadow-lg">
        <form action="" method="POST">

          {% csrf_token %}

          <h2 class="text-center mt-2">Password reset</h2>
          <p>
            Forgotten your password? Enter your email address below, and we’ll email instructions for setting
            a new one.
          </p>
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-success">
                <p>{{ message }}</p>
              </div>
            {% endfor %}
          {% endif %}
          <div class="mb-4">
            <label for="{{ form.username.id_for_label }}" class="form-label">Email</label>
            {{ form.email }}
          </div>
          <div class="text-center">
            <button type="submit" class="btn btn-outline-success">Submit</button>
          </div>
          <div class="text-center mb-3">
            <div>
              <p class="my-0">or</p>
              <a class="link-secondary text-decoration-none" href="{% url 'accounts:login' %}">
                Sign In
              </a>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}