SpecialRecipe/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from recipe.views import RecipesListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recipes/', include('recipe.urls', namespace='recipe')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', RecipesListView.as_view(), name='index'),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

accounts/urls.py
from django.urls import path

from accounts import views as account_view

app_name = 'accounts'

urlpatterns = [
    path('registration/', account_view.UserRegistrationView.as_view(), name='registration'),
    path('login/', account_view.UserLoginView.as_view(), name='login'),
    path('logout/', account_view.LogoutView.as_view(), name='logout'),

    path('user/<slug:slug>/', account_view.UserProfileView.as_view(), name='profile'),
    path('user/<slug:slug>/email/', account_view.UserProfileEmailView.as_view(), name='profile-email'),
    path('user/<slug:slug>/password/', account_view.UserProfilePasswordView.as_view(), name='profile-password'),

    path('verification/send/<str:email>/', account_view.SendVerificationEmailView.as_view(),
         name='send-verification-email'),
    path('verify/<str:email>/<uuid:code>/', account_view.EmailVerificationView.as_view(), name='email-verification'),

    path('password_reset/', account_view.PasswordResetView.as_view(), name='reset_password'),
    path('reset/<uidb64>/<token>/', account_view.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

api/urls.py
from django.urls import include, path

app_name = 'api'

urlpatterns = [
    path('', include('api.recipe.urls', namespace='recipe')),
    path('', include('api.accounts.urls', namespace='accounts')),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),

    path('', include('recipe.urls', namespace='recipe')),
    path('interactions/', include('interactions.urls', namespace='interactions')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('api/v1/', include('api.urls', namespace='api')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

accounts/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView

from accounts import forms as account_forms
from accounts.models import EmailVerification, User
from accounts.tasks import send_verification_email
from common.urls import get_referer_or_default
from common.views import LogoutRequiredMixin, TitleMixin
from utils.uid import is_valid_uuid


class UserRegistrationView(LogoutRequiredMixin, SuccessMessageMixin, TitleMixin, CreateView):
    model = User
    form_class = account_forms.UserRegistrationForm
    template_name = 'accounts/registration.html'
    success_message = 'You have successfully registered!'
    success_url = reverse_lazy('accounts:login')
    title = 'Special Recipe | Registration'


class UserLoginView(LogoutRequiredMixin, TitleMixin, auth_views.LoginView):
    form_class = account_forms.UserLoginForm
    template_name = 'accounts/login.html'
    title = 'Special Recipe | Registration'

    def get(self, request, *args, **kwargs):
        request.session['before_login_url'] = get_referer_or_default(self.request, None)
        return super().get(request, *args, **kwargs)

    def get_success_url(self):
        next_query = self.request.session.get('before_login_url')
        return next_query if next_query else reverse_lazy('accounts:profile', args={self.request.user.slug})

    def form_valid(self, form):
        remember_me = form.cleaned_data.get('remember_me')
        if not remember_me:
            self.request.session.set_expiry(0)
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, 'The entered data is incorrect, please try again.')
        return super().form_invalid(form)


class LogoutView(auth_views.LogoutView):
    def get_redirect_url(self):
        next_page = get_referer_or_default(self.request)
        return next_page


class UserProfileView(SuccessMessageMixin, TitleMixin, UpdateView):
    model = User
    form_class = account_forms.UserProfileForm
    template_name = 'accounts/profile/profile.html'
    title = 'Special Recipe | Account'
    success_message = 'Profile updated successfully!'

    def get_success_url(self):
        return reverse_lazy('accounts:profile', args=(self.object.slug,))

    def form_invalid(self, form):
        self.object.refresh_from_db()
        return super().form_invalid(form)


class UserProfilePasswordView(SuccessMessageMixin, auth_views.PasswordChangeView):
    form_class = account_forms.PasswordChangeForm
    template_name = 'accounts/profile/profile.html'
    title = 'Special Recipe | Password'
    success_message = 'Your password has been successfully updated!'

    def get_success_url(self):
        return reverse_lazy('accounts:profile-password', args={self.request.user.slug})


class UserProfileEmailView(SuccessMessageMixin, auth_views.PasswordChangeView):
    form_class = account_forms.EmailChangeForm
    template_name = 'accounts/profile/profile.html'
    title = 'Special Recipe | Email'
    success_message = 'Your email has been successfully changed!'

    def get_success_url(self):
        return reverse_lazy('accounts:profile-email', args={self.request.user.slug})


class SendVerificationEmailView(LoginRequiredMixin, TitleMixin, TemplateView):
    template_name = 'accounts/email/email_verification_done.html'
    title = 'Special Recipe | Send Verification'
    sending_interval = settings.EMAIL_SEND_INTERVAL_SECONDS

    def get(self, request, *args, **kwargs):
        email = kwargs.get('email')
        user = get_object_or_404(User, email=email)

        if not user.is_request_user_matching(request):
            raise Http404

        seconds_since_last_email = user.seconds_since_last_email_verification()

        if user.is_verified:
            messages.warning(request, 'You have already verified your email.')
        elif seconds_since_last_email < self.sending_interval:
            seconds_left = self.sending_interval - seconds_since_last_email
            messages.warning(request, f'Please wait {seconds_left} to resend the confirmation email.')
        else:
            verification = user.create_email_verification()
            send_verification_email.delay(object_id=verification.id)
        return super().get(request, *args, **kwargs)


class EmailVerificationView(TemplateView):
    template_name = 'accounts/email/email_verification_complete.html'

    def get(self, request, *args, **kwargs):
        code = kwargs.get('code')
        email = kwargs.get('email')
        user = get_object_or_404(User, email=email)

        if not user.is_request_user_matching(request) or not is_valid_uuid(str(code)):
            raise Http404

        verification = get_object_or_404(EmailVerification, user=user, code=code)

        if user.is_verified:
            messages.warning(request, 'Your email has already been verified.')
        elif not verification.is_expired():
            user.verify()
        else:
            messages.warning(request, 'The verification link has expired.')
        return super().get(request, *args, **kwargs)


class PasswordResetView(LogoutRequiredMixin, SuccessMessageMixin, auth_views.PasswordResetView):
    title = 'Special Recipe | Password Reset'
    template_name = 'accounts/password/reset_password.html'
    subject_template_name = 'accounts/password/password_reset_subject.html'
    email_template_name = 'accounts/password/password_reset_email.html'
    form_class = account_forms.PasswordResetForm
    success_url = reverse_lazy('accounts:reset_password')
    success_message = 'We’ve emailed you instructions for setting your password, if an account exists with the email ' \
                      'you entered. You should receive them shortly. If you don’t receive an email, please make sure ' \
                      'you’ve entered the address you registered with, and check your spam folder.'


class PasswordResetConfirmView(LogoutRequiredMixin, SuccessMessageMixin, TitleMixin,
                               auth_views.PasswordResetConfirmView):
    title = 'Special Recipe | Password Reset'
    template_name = 'accounts/password/password_reset_confirm.html'
    form_class = account_forms.SetPasswordForm
    success_url = reverse_lazy('accounts:login')
    success_message = 'Your password has been set. You can now sign into your account with the new password.'

api/accounts/views.py
from django.conf import settings
from django.shortcuts import get_object_or_404
from djoser import email as email_views
from rest_framework import status
from rest_framework.generics import CreateAPIView, UpdateAPIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from accounts.models import EmailVerification, User
from accounts.tasks import send_verification_email
from api.accounts.serializers import EmailVerificationSerializer
from utils.uid import is_valid_uuid


class PasswordResetEmail(email_views.PasswordResetEmail):
    template_name = 'accounts/password/password_reset_email.html'
    subject_template_name = 'accounts/password/password_reset_subject.html'


class SendVerificationEmailCreateAPIView(CreateAPIView):
    queryset = EmailVerification.objects.all()
    serializer_class = EmailVerificationSerializer
    permission_classes = (IsAuthenticated,)
    sending_interval = settings.EMAIL_SEND_INTERVAL_SECONDS

    def create(self, request, *args, **kwargs):
        email = request.data.get('email')
        user = get_object_or_404(User, email=email)

        if not user.is_request_user_matching(request):
            return Response({'detail': 'Not found.'}, status=status.HTTP_404_NOT_FOUND)
        elif user.is_verified:
            return Response({'detail': 'Already verified.'}, status=status.HTTP_400_BAD_REQUEST)

        seconds_since_last_email = user.seconds_since_last_email_verification()

        if seconds_since_last_email < self.sending_interval:
            seconds_left = self.sending_interval - seconds_since_last_email
            response = {
                'detail': 'Messages per minute limit reached.',
                'seconds_left': seconds_left,
            }
            return Response(response, status=status.HTTP_429_TOO_MANY_REQUESTS)
        else:
            verification = user.create_email_verification()
            send_verification_email.delay(object_id=verification.id)
            serializer = self.get_serializer(verification, partial=True)
            return Response(serializer.data, status=status.HTTP_201_CREATED)


class EmailVerificationUpdateAPIView(UpdateAPIView):
    queryset = User.objects.all()
    permission_classes = (IsAuthenticated,)

    def update(self, request, *args, **kwargs):
        code = request.data.get('code')
        email = request.data.get('email')
        user = get_object_or_404(User, email=email)

        if not user.is_request_user_matching(request) or not is_valid_uuid(str(code)):
            return Response({'detail': 'Not found.'}, status=status.HTTP_404_NOT_FOUND)
        elif user.is_verified:
            return Response({'detail': 'Already verified.'}, status=status.HTTP_400_BAD_REQUEST)

        verification = get_object_or_404(EmailVerification, user=user, code=code)
        if not verification.is_expired():
            user.verify()
            return Response(status=status.HTTP_204_NO_CONTENT)
        else:
            return Response({'detail': 'Link was expired.'}, status=status.HTTP_410_GONE)

api/views/accounts.py
from django.conf import settings
from django.shortcuts import get_object_or_404
from djoser import email as email_views
from rest_framework import status
from rest_framework.generics import CreateAPIView, UpdateAPIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from accounts.models import EmailVerification, User
from accounts.tasks import send_verification_email
from api.serializers.accounts import EmailVerificationSerializer
from utils.uid import is_valid_uuid


class PasswordResetEmail(email_views.PasswordResetEmail):
    template_name = 'accounts/password/password_reset_email.html'
    subject_template_name = 'accounts/password/password_reset_subject.html'


class SendVerificationEmailCreateAPIView(CreateAPIView):
    queryset = EmailVerification.objects.all()
    serializer_class = EmailVerificationSerializer
    permission_classes = (IsAuthenticated,)
    sending_interval = settings.EMAIL_SEND_INTERVAL_SECONDS

    def create(self, request, *args, **kwargs):
        email = request.data.get('email')
        user = get_object_or_404(User, email=email)

        if not user.is_request_user_matching(request):
            return Response({'detail': 'Not found.'}, status=status.HTTP_404_NOT_FOUND)
        elif user.is_verified:
            return Response({'detail': 'Already verified.'}, status=status.HTTP_400_BAD_REQUEST)

        seconds_since_last_email = user.seconds_since_last_email_verification()

        if seconds_since_last_email < self.sending_interval:
            seconds_left = self.sending_interval - seconds_since_last_email
            response = {
                'detail': 'Messages per minute limit reached.',
                'seconds_left': seconds_left,
            }
            return Response(response, status=status.HTTP_429_TOO_MANY_REQUESTS)
        else:
            verification = user.create_email_verification()
            send_verification_email.delay(object_id=verification.id)
            serializer = self.get_serializer(verification, partial=True)
            return Response(serializer.data, status=status.HTTP_201_CREATED)


class EmailVerificationUpdateAPIView(UpdateAPIView):
    queryset = User.objects.all()
    permission_classes = (IsAuthenticated,)

    def update(self, request, *args, **kwargs):
        code = request.data.get('code')
        email = request.data.get('email')
        user = get_object_or_404(User, email=email)

        if not user.is_request_user_matching(request) or not is_valid_uuid(str(code)):
            return Response({'detail': 'Not found.'}, status=status.HTTP_404_NOT_FOUND)
        elif user.is_verified:
            return Response({'detail': 'Already verified.'}, status=status.HTTP_400_BAD_REQUEST)

        verification = get_object_or_404(EmailVerification, user=user, code=code)
        if not verification.is_expired():
            user.verify()
            return Response(status=status.HTTP_204_NO_CONTENT)
        else:
            return Response({'detail': 'Link was expired.'}, status=status.HTTP_410_GONE)

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
  <div class="container bg-light min-vh-100">
    <div class="row">
      <div class="container bg-secondary-subtle rounded-4 mt-5 col-md-4 shadow-lg">
        <form action="" method="POST">

          {% csrf_token %}

          <div class="mb-4">
            <h2 class="text-center mt-2">Sign In</h2>
          </div>
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}" role="alert">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          <hr>
          <div class="mb-4">
            <label for="{{ form.username.id_for_label }}" class="form-label">Username or Email</label>
            {{ form.username }}
          </div>
          <div class="mb-4">
            <label for="{{ form.password.id_for_label }}" class="form-label">Password</label>
            {{ form.password }}
          </div>
          <div class="d-flex">
            <div class="form-check me-auto">
              {{ form.remember_me }}
              <label class="form-check-label" for="{{ form.remember_me.id_for_label }}">
                Remember me
              </label>
            </div>
            <div>
              <a href="{% url 'accounts:reset_password' %}" class="link-secondary text-decoration-none">
                Forgot password ?
              </a>
            </div>
          </div>
          <hr>
          <div class="text-center">
            <button type="submit" class="btn btn-outline-success">Submit</button>
          </div>
          <div class="text-center mb-3">
            <div>
              <p class="my-0">or</p>
              <a class="link-secondary text-decoration-none" href="{% url 'accounts:registration' %}">
                Sign Up
              </a>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/accounts/profile.html
{% extends 'recipe/base.html' %}
{% load static %}


{% block content %}
  <div class="container bg-light min-vh-100">
    <div class="row">
      {% if user.id == request.user.id %}
        <div class="col-lg-3 my-3">
          <div class="text-center">
            <img class="rounded-circle" src="{% if user.image %}
                                               {{ user.image.url }}
                                             {% else %}
                                               {% static 'icon/default_user_image.png' %}
                                             {% endif %}" width="192" height="192" alt="default_user_image">
          </div>
          <div>
            <h2 class="text-center text-truncate">{{ user.username }}</h2>
          </div>
          <div class="list-group rounded-top-2 rounded-bottom-2 ">
            <a class="list-group-item list-group-item-action text-dark bg-body-secondary disabled" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                   class="bi bi-house-fill mb-1" viewBox="0 0 16 16">
                <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L8 2.207l6.646
                                6.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.707
                                1.5Z">
                </path>
                <path d="m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6Z"></path>
              </svg>
              Account
            </a>
            <a class="list-group-item list-group-item-action" href="{% url 'password_change' %}">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                   class="bi bi-key-fill mb-1" viewBox="0 0 16 16">
                <path d="M3.5 11.5a3.5 3.5 0 1 1 3.163-5H14L15.5 8 14 9.5l-1-1-1 1-1-1-1 1-1-1-1
                                1H6.663a3.5 3.5 0 0 1-3.163 2zM2.5 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"></path>
              </svg>
              Password
            </a>
            <a class="list-group-item list-group-item-action link-danger" href="{% url 'accounts:logout' %}">
              Logout
            </a>
          </div>
        </div>
        <div class="col-lg-9 my-3">
          <div class="row mt-4">
            <div class="mb-4">
              <h2>{{ user.username }}'s Settings</h2>
            </div>
            {% if form.errors %}
              <div class="alert alert-warning" role="alert">
                {% for field, errors in form.errors.items %}
                    {% for error in errors %}
                      <li>
                        {{ error }}
                      </li>
                    {% endfor %}
                {% endfor %}
              </div>
            {% elif messages %}
              <div class="alert alert-success" role="alert">
                {% for message in messages %}
                  {{ message }}
                {% endfor %}
              </div>
            {% endif %}
            <div class="row">
              <div>
                <form action="" method="POST" enctype="multipart/form-data">

                  {% csrf_token %}

                  <div class="mb-4">
                    <label for="{{ form.username.id_for_label }}" class="form-label">Username</label>
                    {{ form.username }}
                  </div>
                  <div class="mb-4">
                    <label for="{{ form.first_name.id_for_label }}" class="form-label">First Name</label>
                    {{ form.first_name }}
                  </div>
                  <div class="mb-4">
                    <label for="{{ form.last_name.id_for_label }}" class="form-label">Last Name</label>
                    {{ form.last_name }}
                  </div>
                  <div class="mb-4">
                    <label for="{{ form.email.id_for_label }}" class="form-label ">
                      Email
                      {% if not user.is_verified %}
                        (Unverified, click
                        <a class="text-decoration-none" href="{% url 'accounts:send-verification-email' user.email %}">
                          here
                        </a>
                        to send a verification email)
                      {% endif %}
                    </label>
                    {{ form.email }}
                  </div>
                  <div class="mb-4">
                    <label for="{{ form.image.id_for_label }}" class="form-label">Image</label>
                    <div class="input-group">
                      {{ form.image }}
                    </div>
                  </div>
                  <div>
                    <button class="btn btn-outline-success" type="submit">Update</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      {% else %}
        <div class="text-center my-3">
          <img class="rounded-circle" src="{% if user.image %}
                                             {{ user.image.url }}
                                           {% else %}
                                             {% static 'icon/default_user_image.png' %}
                                           {% endif %}"
               width="192" height="192" alt="default_user_image">
        </div>
        <div>
          <h2 class="text-center text-truncate">{{ user.username }}</h2>
        </div>
        <div class="text-center">
          <h4>You cannot view another user's profile.</h4>
        </div>
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/accounts/registration.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
  <div class="container bg-light min-vh-100">
    <div class="row">
      <div class="container bg-secondary-subtle rounded-4 mt-5 col-lg-5 shadow-lg">
        <form action="" method="POST">

          {% csrf_token %}

          <div class="mb-4">
            <h2 class="text-center mt-2">Sign Up</h2>
          </div>
          {% if form.errors %}
            <div class="alert alert-warning" role="alert">
              {% for field, errors in form.errors.items %}
                {% for error in errors %}
                  <ul class="m-0">
                    <li>
                      {{ error }}
                    </li>
                  </ul>
                {% endfor %}
              {% endfor %}
            </div>
          {% endif %}
          <hr>
          <div class="mb-4">
            <label for="{{ form.username.id_for_label }}" class="form-label">Username</label>
            {{ form.username }}
          </div>
          <div class="mb-4">
            <label for="{{ form.email.id_for_label }}" class="form-label">Email address</label>
            {{ form.email }}
          </div>
          <div class="mb-4">
            <label for="{{ form.password1.id_for_label }}" class="form-label">Password</label>
            {{ form.password1 }}
            <div id="passwordHelpBlock" class="container form-text">
              Your password must be 8-20 characters long, contain letters and numbers,
              and must not contain spaces or special characters.
            </div>
          </div>
          <div>
            <label for="{{ form.password2.id_for_label }}" class="form-label">Confirm Password</label>
            {{ form.password2 }}
          </div>
          <hr>
          <div class="text-center">
            <button type="submit" class="btn btn-outline-success">Submit</button>
          </div>
          <div class="text-center mb-3">
            <div>
              <p class="my-0">or</p>
              <a class="link-secondary text-decoration-none" href="{% url 'accounts:login' %}">
                Sign In
              </a>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/accounts/saved_recipes.html
{% extends 'recipe/base.html' %}
{% load static %}


{% block content %}
  <div class="container bg-light min-vh-100">
    <div>
      <h1 class="text-center pt-2">Your bookmarks</h1>
    </div>
    <hr>
    <div class="row">
      {% if saved_recipes %}
        {% for recipe in saved_recipes %}
          <div class="col-lg-3 mb-3">
            {% include 'recipe/inclusion/recipe_card/recipe_card_bookmark_active.html' %}
          </div>
        {% endfor %}
      {% else %}
        <div class="text-center">
          <svg xmlns="http://www.w3.org/2000/svg" width="125" height="125" fill="currentColor"
               class="bi bi-bookmarks my-5" viewBox="0 0 16 16">
            <path d="M2 4a2 2 0 0 1 2-2h6a2 2 0 0 1 2 2v11.5a.5.5 0 0 1-.777.416L7 13.101l-4.223
            2.815A.5.5 0 0 1 2 15.5V4zm2-1a1 1 0 0 0-1 1v10.566l3.723-2.482a.5.5 0 0 1 .554 0L11
            14.566V4a1 1 0 0 0-1-1H4z"></path>
            <path d="M4.268 1H12a1 1 0 0 1 1 1v11.768l.223.148A.5.5 0 0 0 14 13.5V2a2 2 0 0 0-2-2H6a2
            2 0 0 0-1.732 1z"></path>
          </svg>
          <h3 class="text-center">
            Oops... It looks like you don't have any saved recipes yet.
            You can save a recipe by clicking on the bookmark icon on the recipe card.
          </h3>
        </div>
      {% endif %}
    </div>
  </div>
{% endblock %}

{% block script %}
  <script src="{% static 'js/script.js' %}"></script>
{% endblock %}