SpecialRecipe/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from recipe.views import RecipesListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recipes/', include('recipe.urls', namespace='recipe')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', RecipesListView.as_view(), name='index'),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

accounts/urls.py
from django.urls import path

from accounts import views as account_view

app_name = 'accounts'

urlpatterns = [
    path('registration/', account_view.UserRegistrationView.as_view(), name='registration'),
    path('login/', account_view.UserLoginView.as_view(), name='login'),
    path('logout/', account_view.LogoutView.as_view(), name='logout'),

    path('user/<slug:slug>/', account_view.UserProfileView.as_view(), name='profile'),
    path('user/<slug:slug>/email/', account_view.UserProfileEmailView.as_view(), name='profile-email'),
    path('user/<slug:slug>/password/', account_view.UserProfilePasswordView.as_view(), name='profile-password'),

    path('verification/send/<str:email>/', account_view.SendVerificationEmailView.as_view(),
         name='send-verification-email'),
    path('verify/<str:email>/<uuid:code>/', account_view.EmailVerificationView.as_view(), name='email-verification'),

    path('password_reset/', account_view.PasswordResetView.as_view(), name='reset_password'),
    path('reset/<uidb64>/<token>/', account_view.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

api/recipe/urls.py
from django.urls import include, path
from rest_framework import routers

from api.recipe.views import (CategoryModelViewSet, CommentGenericViewSet,
                              IngredientGenericViewSet,
                              RecipeBookmarkGenericViewSet, RecipeModelViewSet)

app_name = 'recipe'

router = routers.DefaultRouter()

router.register(r'recipes', RecipeModelViewSet, basename='recipes')
router.register(r'categories', CategoryModelViewSet, basename='categories')
router.register(r'ingredients', IngredientGenericViewSet, basename='ingredients')
router.register(r'comments', CommentGenericViewSet, basename='comments')
router.register(r'bookmarks', RecipeBookmarkGenericViewSet, basename='bookmarks')

urlpatterns = [
    path('', include(router.urls)),
]

api/urls.py
from django.urls import include, path

app_name = 'api'

urlpatterns = [
    path('', include('api.recipe.urls', namespace='recipe')),
    path('', include('api.accounts.urls', namespace='accounts')),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),

    path('', include('recipe.urls', namespace='recipe')),
    path('interactions/', include('interactions.urls', namespace='interactions')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('api/v1/', include('api.urls', namespace='api')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

recipe/urls.py
from django.urls import path

from recipe.views import RecipeDetailView, RecipesListView

app_name = 'recipe'

urlpatterns = [
    path('', RecipesListView.as_view(), name='index'),
    path('detail/<slug:recipe_slug>/', RecipeDetailView.as_view(), name='detail'),
    path('category/<slug:category_slug>/', RecipesListView.as_view(), name='category'),
]

recipe/models.py
from django.db import models

from recipe.managers import CategoryManager, RecipeManager


class Category(models.Model):
    name = models.CharField(max_length=32)
    slug = models.SlugField(unique=True)

    objects = CategoryManager()

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Recipe(models.Model):
    image = models.ImageField(upload_to='recipe_images')
    name = models.CharField(max_length=32)
    description = models.CharField(max_length=128)
    cooking_description = models.TextField()
    category = models.ForeignKey(to=Category, on_delete=models.PROTECT)
    slug = models.SlugField(unique=True)
    bookmarks = models.ManyToManyField('accounts.User', blank=True, through='interactions.RecipeBookmark')
    views = models.PositiveBigIntegerField(default=0)

    objects = RecipeManager()

    def __str__(self):
        return self.name

    def ingredients(self):
        return self.ingredient_set.all()

    def comments(self):
        return self.recipecomment_set.all().prefetch_related('author')

    def bookmarks_count(self):
        return self.bookmarks.count()


class Ingredient(models.Model):
    name = models.CharField(max_length=256)
    recipe = models.ForeignKey(to=Recipe, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

recipe/forms.py
from django import forms


class SearchForm(forms.Form):
    search = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control me-2',
        'placeholder': 'Enter recipe name',
        'type': 'search',
        'aria-label': 'Search',
        'autocomplete': 'off',
    }))

api/recipe/views.py
from django.db.models import Q
from django.shortcuts import get_object_or_404
from rest_framework import status
from rest_framework.authentication import SessionAuthentication
from rest_framework.mixins import (CreateModelMixin, DestroyModelMixin,
                                   ListModelMixin, UpdateModelMixin)
from rest_framework.permissions import IsAdminUser, IsAuthenticated
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet, ModelViewSet

from api.recipe.pagination import (CategoryPageNumberPagination,
                                   CommentPageNumberPagination,
                                   RecipePageNumberPagination)
from api.recipe.serializers import (CategorySerializer, CommentSerializer,
                                    IngredientSerializer,
                                    RecipeBookmarkSerializer, RecipeSerializer)
from interactions.models import RecipeBookmark
from recipe.models import Category, Ingredient, Recipe


class CategoryModelViewSet(ModelViewSet):
    model = Category
    serializer_class = CategorySerializer
    pagination_class = CategoryPageNumberPagination

    def get_queryset(self):
        queryset = self.model.objects.cached_queryset()
        return queryset.order_by('name')

    def get_permissions(self):
        if self.action in ('create', 'update', 'destroy'):
            self.permission_classes = (IsAdminUser,)
        return super().get_permissions()


class RecipeModelViewSet(ModelViewSet):
    model = Recipe
    serializer_class = RecipeSerializer
    pagination_class = RecipePageNumberPagination
    ordering = ('name',)

    def get_queryset(self):
        queryset = self.model.objects.cached_queryset()

        selected_category_slug = self.request.query_params.get('category_slug')
        search = self.request.query_params.get('search')

        if search:
            queryset = queryset.filter(Q(name__icontains=search) | Q(description__icontains=search))
        elif selected_category_slug:
            queryset = queryset.filter(category__slug=selected_category_slug)

        return queryset.order_by(*self.ordering)

    def get_permissions(self):
        if self.action in ('create', 'update', 'destroy'):
            self.permission_classes = (IsAdminUser,)
        return super().get_permissions()


class IngredientGenericViewSet(CreateModelMixin, UpdateModelMixin, GenericViewSet, DestroyModelMixin):
    queryset = Ingredient.objects.order_by('name')
    serializer_class = IngredientSerializer

    def get_permissions(self):
        if self.action in ('create', 'update', 'destroy'):
            self.permission_classes = (IsAdminUser,)
        return super().get_permissions()


class CommentGenericViewSet(GenericViewSet, ListModelMixin, CreateModelMixin):
    authentication_classes = (SessionAuthentication,)
    serializer_class = CommentSerializer
    pagination_class = CommentPageNumberPagination

    def list(self, request, *args, **kwargs):
        recipe_id = request.GET.get('recipe_id')
        if not recipe_id:
            return Response({'recipe_id': 'This field is required.'}, status=status.HTTP_400_BAD_REQUEST)
        recipe = get_object_or_404(Recipe, id=recipe_id)
        comments = recipe.comments().order_by('-created_date')
        paginated_comments = self.paginate_queryset(comments)
        serializer = self.serializer_class(paginated_comments, many=True)
        return self.get_paginated_response(serializer.data)

    def create(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save(author=request.user)
        return Response(serializer.data, status=status.HTTP_201_CREATED)

    def get_permissions(self):
        if self.action in ('create', 'update', 'destroy'):
            self.permission_classes = (IsAuthenticated,)
        return super().get_permissions()


class RecipeBookmarkGenericViewSet(GenericViewSet, ListModelMixin, CreateModelMixin, DestroyModelMixin):
    model = RecipeBookmark
    authentication_classes = (SessionAuthentication,)
    serializer_class = RecipeBookmarkSerializer
    permission_classes = (IsAuthenticated,)
    pagination_class = RecipePageNumberPagination
    ordering = ('-created_date',)

    def list(self, request, *args, **kwargs):
        bookmarks = RecipeBookmark.objects.user_bookmarks(request.user).order_by(*self.ordering)
        paginated_bookmarks = self.paginate_queryset(bookmarks)
        serializer = self.serializer_class(paginated_bookmarks, many=True)
        return self.get_paginated_response(serializer.data)

    def create(self, request, *args, **kwargs):
        recipe_id = request.data.get('recipe_id')
        if not recipe_id:
            return Response({'recipe_id': 'This field is required.'}, status=status.HTTP_400_BAD_REQUEST)
        recipe = get_object_or_404(Recipe, id=recipe_id)
        recipe.bookmarks.add(request.user, through_defaults=None)
        bookmark = self.model.objects.get(recipe=recipe, user=request.user)
        serializer = self.serializer_class(bookmark)
        return Response(serializer.data, status=status.HTTP_201_CREATED)

    def destroy(self, request, *args, **kwargs):
        recipe_id = kwargs.get('pk')
        recipe = get_object_or_404(Recipe, id=recipe_id)
        recipe.bookmarks.remove(request.user)
        return Response(status=status.HTTP_204_NO_CONTENT)

api/views/recipe.py
from django.db.models import Q
from django.shortcuts import get_object_or_404
from rest_framework import status
from rest_framework.authentication import SessionAuthentication
from rest_framework.mixins import (CreateModelMixin, DestroyModelMixin,
                                   ListModelMixin, UpdateModelMixin)
from rest_framework.permissions import IsAdminUser, IsAuthenticated
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet, ModelViewSet

from api.pagination import (CategoryPageNumberPagination,
                            CommentPageNumberPagination,
                            RecipePageNumberPagination)
from api.serializers.recipe import (CategorySerializer, CommentSerializer,
                                    IngredientSerializer,
                                    RecipeBookmarkSerializer, RecipeSerializer)
from recipe.models import Category, Comment, Ingredient, Recipe, RecipeBookmark


class CategoryModelViewSet(ModelViewSet):
    model = Category
    serializer_class = CategorySerializer
    pagination_class = CategoryPageNumberPagination

    def get_queryset(self):
        queryset = self.model.objects.get_cached_queryset()
        return queryset.order_by('name')

    def get_permissions(self):
        if self.action in ('create', 'update', 'destroy'):
            self.permission_classes = (IsAdminUser,)
        return super().get_permissions()


class RecipeModelViewSet(ModelViewSet):
    model = Recipe
    serializer_class = RecipeSerializer
    pagination_class = RecipePageNumberPagination
    ordering = ('name',)

    def get_queryset(self):
        queryset = self.model.objects.get_cached_queryset()

        selected_category_slug = self.request.query_params.get('category_slug')
        search = self.request.query_params.get('search')

        if search:
            queryset = queryset.filter(Q(name__icontains=search) | Q(description__icontains=search))
        elif selected_category_slug:
            queryset = queryset.filter(category__slug=selected_category_slug)

        return queryset.order_by(*self.ordering)

    def get_permissions(self):
        if self.action in ('create', 'update', 'destroy'):
            self.permission_classes = (IsAdminUser,)
        return super().get_permissions()


class IngredientGenericViewSet(CreateModelMixin, UpdateModelMixin, GenericViewSet, DestroyModelMixin):
    queryset = Ingredient.objects.order_by('name')
    serializer_class = IngredientSerializer

    def get_permissions(self):
        if self.action in ('create', 'update', 'destroy'):
            self.permission_classes = (IsAdminUser,)
        return super().get_permissions()


class CommentGenericViewSet(GenericViewSet, ListModelMixin, CreateModelMixin):
    authentication_classes = (SessionAuthentication,)
    serializer_class = CommentSerializer
    pagination_class = CommentPageNumberPagination

    def list(self, request, *args, **kwargs):
        recipe_id = request.GET.get('recipe_id')
        if not recipe_id:
            return Response({'recipe_id': 'This field is required.'}, status=status.HTTP_400_BAD_REQUEST)
        comments = Comment.objects.filter(recipe_id=recipe_id).order_by('-created_date')
        paginated_comments = self.paginate_queryset(comments)
        serializer = self.serializer_class(paginated_comments, many=True)
        return self.get_paginated_response(serializer.data)

    def create(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save(author=request.user)
        return Response(serializer.data, status=status.HTTP_201_CREATED)

    def get_permissions(self):
        if self.action in ('create', 'update', 'destroy'):
            self.permission_classes = (IsAuthenticated,)
        return super().get_permissions()


class RecipeBookmarkGenericViewSet(GenericViewSet, ListModelMixin, CreateModelMixin, DestroyModelMixin):
    model = RecipeBookmark
    authentication_classes = (SessionAuthentication,)
    serializer_class = RecipeBookmarkSerializer
    permission_classes = (IsAuthenticated,)
    pagination_class = RecipePageNumberPagination
    ordering = ('-created_date',)

    def list(self, request, *args, **kwargs):
        bookmarks = self.model.objects.get_user_bookmarks(request.user).order_by(*self.ordering)
        paginated_bookmarks = self.paginate_queryset(bookmarks)
        serializer = self.serializer_class(paginated_bookmarks, many=True)
        return self.get_paginated_response(serializer.data)

    def create(self, request, *args, **kwargs):
        recipe_id = request.data.get('recipe_id')
        if not recipe_id:
            return Response({'recipe_id': 'This field is required.'}, status=status.HTTP_400_BAD_REQUEST)
        recipe = get_object_or_404(Recipe, id=recipe_id)
        recipe.bookmarks.add(request.user, through_defaults=None)
        bookmark = self.model.objects.get(recipe=recipe, user=request.user)
        serializer = self.serializer_class(bookmark)
        return Response(serializer.data, status=status.HTTP_201_CREATED)

    def destroy(self, request, *args, **kwargs):
        recipe_id = kwargs.get('pk')
        recipe = get_object_or_404(Recipe, id=recipe_id)
        recipe.bookmarks.remove(request.user)
        return Response(status=status.HTTP_204_NO_CONTENT)

templates/recipe/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
  <div class="container bg-light min-vh-100">
    <div class="row">
      <div class="col-lg-3 my-2">
        <h1>Recipes</h1>
        <form class="d-flex mb-2" action="{% url 'recipe:index' %}" role="search" method="get">
          {{ form.search }}
          <button class="btn btn-outline-success" type="submit">Find</button>
        </form>
        <hr>
        <div class="list-group">
          <a class="list-group-item list-group-item-action{% if not selected_category_slug and not request.GET.search %}
                                                            text-dark bg-body-secondary disabled
                                                          {% endif %}"
             href="{% url 'recipe:index' %}">
            <span>All Recipes</span>
          </a>
          {% for category in categories %}
            <a class="list-group-item list-group-item-action {% if selected_category_slug == category.slug %}
                                                               text-dark bg-body-secondary disabled
                                                             {% endif %}"
               href="{% url 'recipe:category' category.slug %}">
              <span>{{ category.name }}</span>
            </a>
          {% endfor %}
          {% if has_more_categories %}
            <button id="show-more-categories-btn" class="list-group-item list-group-item-action text-primary"
                    data-page="2" data-selected-category-slug="{{ selected_category_slug }}">
              Show more&hellip;
            </button>
          {% endif %}
        </div>
      </div>
      <div class="col-lg-9 my-2">
        <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel" data-pause="hover">
          <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"
                    aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
                    aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
                    aria-label="Slide 3"></button>
          </div>
          <div class="carousel-inner rounded-2">
            {% for recipe in popular_recipes %}
              <a href="{% url 'recipe:detail' recipe.slug %}">
                <div class="carousel-item {% if forloop.counter0 == 0 %} active {% endif %}">
                  <img src="{{ recipe.image.url }}" class="carousel-img d-block w-100" alt="carousel_first_image">
                  <div class="carousel-caption d-none d-md-block bg-dark bg-opacity-25 rounded-2 p-0 pb-2">
                    <h1 class="text-light">{{ recipe.name }}</h1>
                    <h4 class="text-light">{{ recipe.description }}</h4>
                  </div>
                </div>
              </a>
            {% endfor %}
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
                  data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
                  data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
        {% if object_list %}
          <div class="row mt-4">
            {% for recipe in object_list %}
              <div class="col-lg-4 col-md-6 mb-3">
                {% include 'recipe/inclusion/recipe_card.html' %}
              </div>
            {% endfor %}
          </div>
          {% include 'recipe/inclusion/pagination.html' %}
        {% else %}
          <div class="text-center my-2">
            <h1>Nothing was found</h1>
            <hr>
            <div>
              <img class="mb-4 mt-2" src="{% static 'icon/magnifying-glass.svg' %}" alt="magnifying-glass" width="100"
                   height="100">
              <h4>
                Looks like we couldn't find what you're looking for.
              </h4>
            </div>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

{% block script %}
  <script type="module" src="{% static 'js/script.js' %}"></script>
{% endblock %}

templates/recipe/recipe_bookmarks.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
  <div class="container bg-light min-vh-100">
    <div>
      <h1 class="text-center pt-2">{{ user.username }} bookmarks</h1>
    </div>
    <hr>
    <div id="bookmarks-wrp" class="row">
      {% if object_list %}
        {% for bookmark in object_list %}
          {% with bookmark.recipe as recipe %}
            <div class="col-lg-3 mb-3">
              {% include 'recipe/inclusion/recipe_card.html' %}
            </div>
          {% endwith %}
        {% endfor %}
      {% else %}
        <div class="text-center">
          <svg xmlns="http://www.w3.org/2000/svg" width="125" height="125" fill="currentColor"
               class="bi bi-bookmarks my-5" viewBox="0 0 16 16">
            <path d="M2 4a2 2 0 0 1 2-2h6a2 2 0 0 1 2 2v11.5a.5.5 0 0 1-.777.416L7 13.101l-4.223
            2.815A.5.5 0 0 1 2 15.5V4zm2-1a1 1 0 0 0-1 1v10.566l3.723-2.482a.5.5 0 0 1 .554 0L11
            14.566V4a1 1 0 0 0-1-1H4z"></path>
            <path d="M4.268 1H12a1 1 0 0 1 1 1v11.768l.223.148A.5.5 0 0 0 14 13.5V2a2 2 0 0 0-2-2H6a2
            2 0 0 0-1.732 1z"></path>
          </svg>
          <h3 class="text-center">
            Oops... It looks like you don't have any saved recipes yet.
            You can save a recipe by clicking on the bookmark icon on the recipe card.
          </h3>
        </div>
      {% endif %}
    </div>
  </div>
{% endblock %}

{% block script %}
  <script type="module" src="{% static 'js/script.js' %}"></script>
{% endblock %}

templates/recipe/recipe_description.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load humanize %}


{% block content %}
  <div class="container bg-light min-vh-100">
    <div class="row">
      <div class="col-lg-8 my-2">
        <div>
          <img class="img-fluid rounded-3" src="{{ object.image.url }}" alt="recipe_image">
        </div>
        <div class="container overflow-x-auto">
          <h1 class="text-break my-2">{{ object.name }}</h1>
          {{ object.cooking_description|safe }}
        </div>
      </div>
      <div class="col-lg-4 my-2">
        <div class="container mb-3">
          <h2 class="text-center">Ingredients</h2>
          <hr>
          <div class="container d-flex mb-3 justify-content-center">
            <ul class="list-group list-group-flush">
              {% for ingredient in ingredients %}
                <li class="list-group-item list-group-item-action d-flex bg-light">
                  <div>
                    <input class="form-check-input me-2" type="checkbox" id="IngredientCheckbox{{ forloop.counter0 }}">
                  </div>
                  <label class="form-check-label text-break" for="IngredientCheckbox{{ forloop.counter0 }}">
                    {{ ingredient.name }}
                  </label>
                </li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-8">
        <hr>
        <div class="mb-3">
          <h3>{{ comments_count }} {% if comments_count == 1 %} Comment {% else %} Comments {% endif %}</h3>
        </div>
        <div class="d-flex mb-3">
          <img class="me-3 rounded-circle"
               src="{% if user.is_authenticated and user.image %}
                        {{ user.image.url }}
                    {% else %}
                      {% static 'img/default_user_image.png' %}
                    {% endif %}" alt="user-image" width="40" height="40">
          <form id="add-comment-form" method="POST" class="w-100" data-recipe-id="{{ object.id }}">

            {% csrf_token %}

            {% if user.is_authenticated %}
              <div class="input-group mb-3">
                {{ form.text }}
                <button class="btn btn-outline-success" type="submit" id="comment-submit">Comment</button>
              </div>
            {% else %}
              <div class="input-group">
                {{ form.text|attr:'disabled' }}
                <button class="btn btn-outline-success" type="submit" id="comment-submit" disabled>Comment</button>
              </div>
              <p>
                <a href="{% url 'accounts:login' %}">Sign In</a> or
                <a href="{% url 'accounts:registration' %}">Sign Up</a> to leave comments.
              </p>
            {% endif %}
          </form>
        </div>
        <div id="comments-wrp" class="container">
          {% if comments %}
            {% for comment in comments %}
              <div class="d-flex align-items-start mb-4">
                <a href="{% url 'accounts:profile' comment.author.slug %}">
                  <img class="me-3 rounded-circle" src="{% if comment.author.image %}
                                                          {{ comment.author.image.url }}
                                                        {% else %}
                                                          {% static 'img/default_user_image.png' %}
                                                        {% endif %}" alt="user-image" width="40" height="40">
                </a>
                <div>
                  <a class="fs-5 me-1 link link-dark text-decoration-none"
                     href="{% url 'accounts:profile' comment.author.slug %}">{{ comment.author.username }}</a>
                  <span class="text-body-secondary">{{ comment.created_date|naturaltime }}</span>
                  <p class="text-break">{{ comment.text }}</p>
                </div>
              </div>
            {% endfor %}
          {% else %}
            <div id="no-comments" class="container text-center mb-5">
              <img class="mb-4" src="{% static 'icon/comment.svg' %}" alt="comment" width="125" height="125">
              <h4>Looks like no one has left a comment yet, be the first!</h4>
            </div>
          {% endif %}
        </div>
        {% if has_more_comments %}
          <div class="mb-4 text-center list-group">
            <button id="show-more-comments-btn" type="button"
                    class="list-group-item list-group-item-action text-primary" data-page="2"
                    data-recipe-id="{{ object.id }}">
              Show more
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                   class="bi bi-caret-down" viewBox="0 0 16 16">
                <path d="M3.204 5h9.592L8 10.481 3.204 5zm-.753.659 4.796 5.48a1 1 0 0 0 1.506 0l4.796-5.48c.566-.647.106-1.659-.753-1.659H3.204a1 1 0 0 0-.753 1.659z"></path>
              </svg>
            </button>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

{% block script %}
  <script type="module" src="{% static 'js/script.js' %}"></script>
{% endblock %}